CREATE TABLE "Clasificacion" (
  "Cat_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Cat_nombre" varchar(50) NOT NULL
);

CREATE TABLE "Producto" (
  "Prod_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Prod_codigo" int UNIQUE NOT NULL,
  "Prod_nombre" varchar(50) NOT NULL,
  "Prod_tamaño" int,
  "Prod_imagen" text[],
  "Prod_descripcion" varchar(200),
  "Prod_precio" numeric(10,2) NOT NULL,
  "Prod_cantidad" int DEFAULT 0
);

CREATE TABLE "Producto_Clasificacion" (
  "Prod_id" int NOT NULL,
  "Cat_id" int NOT NULL,
  PRIMARY KEY ("Prod_id", "Cat_id")
);

CREATE TABLE "Almacen" (
  "Alm_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Alm_nombre" varchar(50) NOT NULL,
  "Alm_direccion" varchar(100),
  "Alm_telefono" varchar(20)
);

CREATE TABLE "Stock" (
  "Alm_id" int NOT NULL,
  "Prod_id" int NOT NULL,
  "Stk_cantidad" int NOT NULL DEFAULT 0,
  "Stk_minimo" int NOT NULL DEFAULT 0,
  PRIMARY KEY ("Alm_id", "Prod_id")
);

CREATE TABLE "Proveedor" (
  "Prov_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Prov_razonSocial" varchar(50) NOT NULL,
  "Prov_nit" int UNIQUE NOT NULL,
  "Prov_responsable" varchar(70),
  "Prov_imagen" text[],
  "Prov_correo" varchar(70),
  "Prov_telefono" varchar(20)
);

CREATE TABLE "Sede" (
  "Sed_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Prov_id" int NOT NULL,
  "Sed_nombre" varchar(50) NOT NULL,
  "Sed_direccion" varchar(100),
  "Sed_telefono" varchar(20)
);

CREATE TABLE "Comercia" (
  "Com_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Prod_id" int NOT NULL,
  "Prov_id" int NOT NULL,
  "Com_codigo" int NOT NULL,
  "Com_fecha" timestamp DEFAULT (now()),
  "Com_responsable" varchar(70)
);

CREATE TABLE "Movimiento" (
  "Mov_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Prod_id" int NOT NULL,
  "Alm_id" int NOT NULL,
  "Mov_tipo" varchar(10) NOT NULL,
  "Mov_cantidad" int NOT NULL,
  "Mov_observacion" varchar(100),
  "Mov_fecha" timestamp DEFAULT (now())
);

ALTER TABLE "Producto_Clasificacion" ADD FOREIGN KEY ("Prod_id") REFERENCES "Producto" ("Prod_id");

ALTER TABLE "Producto_Clasificacion" ADD FOREIGN KEY ("Cat_id") REFERENCES "Clasificacion" ("Cat_id");

ALTER TABLE "Stock" ADD FOREIGN KEY ("Alm_id") REFERENCES "Almacen" ("Alm_id");

ALTER TABLE "Stock" ADD FOREIGN KEY ("Prod_id") REFERENCES "Producto" ("Prod_id");

ALTER TABLE "Sede" ADD FOREIGN KEY ("Prov_id") REFERENCES "Proveedor" ("Prov_id");

ALTER TABLE "Comercia" ADD FOREIGN KEY ("Prod_id") REFERENCES "Producto" ("Prod_id");

ALTER TABLE "Comercia" ADD FOREIGN KEY ("Prov_id") REFERENCES "Proveedor" ("Prov_id");

ALTER TABLE "Movimiento" ADD FOREIGN KEY ("Prod_id") REFERENCES "Producto" ("Prod_id");

ALTER TABLE "Movimiento" ADD FOREIGN KEY ("Alm_id") REFERENCES "Almacen" ("Alm_id");
